export const GET_ALL_EXPENSES = 'GET_ALL_EXPENSES';
export const GET_SINGLE_EXPENSE = 'GET_SINGLE_EXPENSE';
export const GET_TOTAL_EXPENSE = 'GET_TOTAL_EXPENSE';
export const GET_EXPENSE_EDIT_HISTORY = 'GET_EXPENSE_EDIT_HISTORY';
export const GET_DO_DETAILS_FOR_EXPENSE = 'GET_DO_DETAILS_FOR_EXPENSE';
